import type { Metadata } from 'next'

import React from 'react'

import { Header } from '@/widgets/header/Header'

// import { Header } from '@/stories/Header'

import '@/styles/index.scss'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang={'en'} suppressHydrationWarning>
      <body>
        <Header isAuthenticated notificationsCount={12} />
        {children}
      </body>
    </html>
  )
}
